In [1]:
import glob
import time
import numpy as np
np.set_printoptions(suppress=True)

from SmoothSparseWeights_CVXOPT import *

In [2]:
# exampleName="cheburashka"
# poses_folder="poses-2"
# poses_ind=7
# clip_k=4
# handle_num=11


# exampleName="cow"
# poses_folder="poses-2"
# poses_ind=5
# clip_k=4
# handle_num=15


exampleName="wolf"
poses_folder="poses-1"
poses_ind=2
clip_k=4
handle_num=21



weights = {'W_spatial': 0.0}

In [3]:
#### read obj file

### rest_poses:
vertices_obj_path="./models/"+exampleName+"-all/"+exampleName+".obj"
mesh0=TriMesh.FromOBJ_FileName(vertices_obj_path)

### other poses
vertices_obj_dir="./models/"+exampleName+"-all/"+poses_folder+"/"
filenames=glob.glob(vertices_obj_dir+"*.obj")
print(filenames)

mesh1_list=[]
for i in range(len(filenames)):
    mesh1_list.append(TriMesh.FromOBJ_FileName(filenames[i]))


vertices1=vertices1_temp=np.hstack((np.asarray(mesh0.vs),np.ones((len(mesh0.vs),1))))
vertices2=vertices2_temp=np.asarray(mesh1_list[0].vs)
for i in range(1,len(mesh1_list)):
    vertices1=np.hstack((vertices1, vertices1_temp))
    vertices2=np.hstack((vertices2, np.asarray(mesh1_list[i].vs)))
print(vertices1.shape) 
print(vertices2.shape) 


['./models/wolf-all/poses-1/wolf-1.obj', './models/wolf-all/poses-1/wolf-2.obj', './models/wolf-all/poses-1/wolf-3.obj', './models/wolf-all/poses-1/wolf-4.obj', './models/wolf-all/poses-1/wolf-5.obj', './models/wolf-all/poses-1/wolf-6.obj']
(5075, 24)
(5075, 18)


In [4]:
#### read our output of simplex_hull.py 
results_path="./results_pipeline/"+exampleName+"-"+str(handle_num)+"/result.txt"
endmembers, mixing_weights=load_result(results_path)
### endmembers shape is handle * poses * 12??

# ### this is to make sure the 3*4 or 4*3 error does not happen.
# endmembers=endmembers.reshape((-1, 4, 3))
# endmembers=np.transpose(endmembers, (0,2,1))
# endmembers=endmembers.reshape((len(mixing_weights), -1, 12))


endmembers=endmembers.reshape((len(mixing_weights),-1))
mixing_weights=mixing_weights.T


print (endmembers.shape)
print (mixing_weights.shape)
print (mixing_weights[:3])
mixing_weights_clip, grad_zero_indices=clip_first_k_values(mixing_weights, clip_k)
print (mixing_weights_clip[:3])
print ((col_major(mixing_weights_clip)[grad_zero_indices]).sum()) ### should be zero

(21, 72)
(5075, 21)
[[0.1589514  0.0000593  0.00474596 0.00048292 0.0000278  0.03343458
  0.07699286 0.17446554 0.03199314 0.00009963 0.01256247 0.12470764
  0.09002658 0.0000002  0.00000122 0.00001448 0.01316137 0.00123948
  0.00000147 0.00000064 0.27703134]
 [0.15856047 0.00005942 0.00472487 0.0004812  0.00002775 0.03355878
  0.07708042 0.17432981 0.03208895 0.00009982 0.01256983 0.12475939
  0.08994991 0.0000002  0.00000122 0.00001445 0.01320413 0.00123941
  0.00000147 0.00000064 0.27724787]
 [0.15566619 0.00006021 0.00463952 0.00047399 0.00002755 0.03405925
  0.07742135 0.17335098 0.03247172 0.00010021 0.01264691 0.12530878
  0.08969101 0.0000002  0.00000124 0.00001417 0.01345853 0.00124074
  0.00000144 0.00000064 0.27936539]]
[[0.1589514  0.         0.         0.         0.         0.
  0.         0.17446554 0.         0.         0.         0.12470764
  0.         0.         0.         0.         0.         0.
  0.         0.         0.27703134]
 [0.15856047 0.         0.         

In [5]:
scale=find_scale(vertices1)
print (scale)

25.309374465859957


In [6]:
recovered_vertices2=recover_vertices(mixing_weights, vertices1, endmembers)
print (E_RMS_kavan2010(vertices2, recovered_vertices2, scale))

2.90071396789943e-09


In [7]:
recovered_vertices2=recover_vertices(mixing_weights_clip, vertices1, endmembers)
print (E_RMS_kavan2010(vertices2, recovered_vertices2, scale))

initials={'x': col_major(mixing_weights_clip.reshape((-1,len(endmembers)))).reshape((-1,1))}
print (initials['x'].shape)

start=time.time()

res=run(mesh0, mesh1_list, weights, endmembers, mixing_weights.ravel(), grad_zero_indices, initials=initials)

res=res.reshape(mixing_weights.shape)
end=time.time()
print("using time: ", end-start)

recovered_vertices2=recover_vertices(res, vertices1, endmembers)
print (E_RMS_kavan2010(vertices2, recovered_vertices2, scale))

11053.189538523577
(106575, 1)
(5075, 24)
(5075, 18)
5075 6 21
W_spatial 0.0
     pcost       dcost       gap    pres   dres
 0: -2.8654e+06 -3.6498e+06  1e+07  1e+01  1e-15
 1: -2.8627e+06 -3.6870e+06  1e+07  7e+00  1e-15
 2: -2.8612e+06 -3.7371e+06  9e+06  6e+00  1e-15
 3: -2.8541e+06 -3.7391e+06  5e+06  3e+00  1e-15
 4: -2.8531e+06 -3.7637e+06  5e+06  2e+00  1e-15
 5: -2.8509e+06 -3.7559e+06  4e+06  2e+00  1e-15
 6: -2.8400e+06 -3.8370e+06  3e+06  1e+00  1e-15
 7: -2.8349e+06 -3.7721e+06  3e+06  8e-01  1e-15
 8: -2.8297e+06 -3.5831e+06  2e+06  5e-01  1e-15
 9: -2.8244e+06 -3.5625e+06  2e+06  3e-01  1e-15
10: -2.8198e+06 -3.5230e+06  2e+06  2e-01  1e-15
11: -2.8188e+06 -3.5144e+06  1e+06  2e-01  1e-15
12: -2.8163e+06 -3.5108e+06  1e+06  2e-01  1e-15
13: -2.8137e+06 -3.4583e+06  1e+06  2e-01  1e-15
14: -2.8090e+06 -3.4435e+06  1e+06  1e-01  1e-15
15: -2.8054e+06 -3.3530e+06  1e+06  1e-01  1e-15
16: -2.8014e+06 -3.3323e+06  1e+06  8e-02  1e-15
17: -2.7954e+06 -3.1082e+06  6e+05  4e-02 

In [8]:
print (res.reshape((-1, len(endmembers)))[:3]) ### should have same zeros as initial input.
print ((col_major(res)[grad_zero_indices]).sum()) ### should be zero
print ((col_major(res)[grad_zero_indices]).max()) ### should be zero

[[ 0.0314606   0.00000184 -0.00000578 -0.0000056  -0.00000404 -0.00000579
  -0.0000058   0.43806026 -0.00000579 -0.00000337 -0.00000581  0.02142753
  -0.0000058  -0.00000023  0.00000076  0.00003852 -0.00000582 -0.00000553
   0.00000853 -0.00000184  0.50906316]
 [ 0.03174131  0.00000176 -0.00000578 -0.0000056  -0.00000408 -0.00000579
  -0.0000058   0.44561361 -0.00000579 -0.0000034  -0.00000581  0.02104947
  -0.0000058  -0.00000022  0.00000085  0.00003823 -0.00000582 -0.00000553
   0.00000835 -0.00000173  0.50160759]
 [ 0.03228857  0.0000017  -0.00000578 -0.00000562 -0.00000413 -0.00000579
  -0.0000058   0.47293269 -0.00000579 -0.00000344 -0.00000581  0.01962018
  -0.0000058  -0.00000019  0.00000115  0.00003764 -0.00000582 -0.00000554
   0.00000769 -0.00000153  0.47517143]]
-9.020562075079397e-17
0.03083508822633423


In [9]:
print (((1-res.sum(axis=-1))**2).sum()/len(res))
print (res.min(), res.max())

2.1453227758057872e-32
-1.0020860305304335e-05 0.9975009192528367


In [10]:
recover_diff= (res.dot(endmembers)-mixing_weights.dot(endmembers))
recover_diff= (recover_diff**2).sum()
print (recover_diff)

252856541.8422539


In [11]:
# #### read gt per vertex transformation 
# groundtruth_names=glob.glob("./models/"+exampleName+"-all/"+exampleName+"-*.DMAT")
# print(groundtruth_names)

# gt_all=None
# for i in range(len(groundtruth_names)):
#     gt=load_DMAT(groundtruth_names[i])
#     gt=gt.T
#     gt=gt.reshape((-1,4,3))
#     gt=np.transpose(gt, (0,2,1)).reshape((-1,12))
#     if gt_all is None:
#         gt_all=gt
#     else:
#         gt_all=np.hstack((gt_all, gt))
    
# print(gt_all.shape)


In [12]:
#### read gt per vertex mixing weights 
groundtruth_names=glob.glob("./models/"+exampleName+"-all/"+exampleName+".DMAT")
print(groundtruth_names)
gt=load_DMAT(groundtruth_names[0])
gt_mixing_weights=gt.T.copy()
print (gt_mixing_weights.shape)

print (((gt_mixing_weights.sum(axis=-1)-1)**2).sum())

['./models/wolf-all/wolf.DMAT']
(5075, 21)
5.575027928616619e-29


In [13]:
### load groundtruth endmember
groundtruth_names=glob.glob("./models/"+exampleName+"-all/"+poses_folder+"/"+exampleName+"-*.Tmat")
print(groundtruth_names)

gt_handles=None
for i in range(len(groundtruth_names)):
    gt=load_Tmat(groundtruth_names[i])
    gt=gt.reshape((-1,4,3))
    gt=np.transpose(gt, (0,2,1)).reshape((-1,12))
    if gt_handles is None:
        gt_handles=gt
    else:
        gt_handles=np.hstack((gt_handles, gt))
    
print(gt_handles.shape)
gt_handles=gt_handles.reshape(len(groundtruth_names), -1, 12)

gt_handles=np.transpose(gt_handles.reshape(-1, len(groundtruth_names), 12), (1,0,2)) ### is this true?

print(gt_handles.shape)

for i in range(len(gt_handles)):
    print (gt_handles[i][2].reshape((3,4)))

test=gt_handles[1][2].reshape((3,4))[:,:3]
print (test.T.dot(test))

['./models/wolf-all/poses-1/wolf-1.Tmat', './models/wolf-all/poses-1/wolf-2.Tmat', './models/wolf-all/poses-1/wolf-3.Tmat', './models/wolf-all/poses-1/wolf-4.Tmat', './models/wolf-all/poses-1/wolf-5.Tmat', './models/wolf-all/poses-1/wolf-6.Tmat']
(21, 72)
(6, 21, 12)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[ 0.963816   0.259295   0.0618401  0.769371 ]
 [-0.215014   0.893333  -0.394619   1.05772  ]
 [-0.157567   0.367044   0.916761   2.30098  ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[ 0.99999966 -0.00000045 -0.00000019]
 [-0.00000045  0.99999904  0.00000028]
 [-0.00000019  0.00000028  0.99999908]]


In [22]:
### plot handles corresponding to gt mixing weights, recovered mixing weights, and post-processed mixing weights.
###

eps=1e-10

# Vertices=vertices2[:,poses_ind*3:poses_ind*3+3]

## use recovered vertices instead.
recovered_vertices2=recover_vertices(res, vertices1, endmembers).reshape((len(vertices1),-1))
Vertices=recovered_vertices2[:,poses_ind*3:poses_ind*3+3]


gt_handle_position=gt_mixing_weights.T.dot(Vertices)/(gt_mixing_weights.T.sum(axis=-1)[...,np.newaxis]+eps)
recovered_handle_position=mixing_weights.T.dot(Vertices)/(mixing_weights.T.sum(axis=-1)[...,np.newaxis]+eps)
cliped_handle_position=mixing_weights_clip.T.dot(Vertices)/(mixing_weights_clip.T.sum(axis=-1)[...,np.newaxis]+eps)
postprocessed_handle_position=res.T.dot(Vertices)/(res.T.sum(axis=-1)[...,np.newaxis]+eps)

%matplotlib 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig= plt.figure()
ax=fig.add_subplot(111, projection='3d')

ax.scatter(gt_handle_position[:,0],gt_handle_position[:,1], gt_handle_position[:,2], c='k', s=50)
ax.scatter(recovered_handle_position[:,0],recovered_handle_position[:,1], recovered_handle_position[:,2], c='r', s=50)
# ax.scatter(cliped_handle_position[:,0],cliped_handle_position[:,1], cliped_handle_position[:,2], c='g', s=50)
ax.scatter(postprocessed_handle_position[:,0],postprocessed_handle_position[:,1], postprocessed_handle_position[:,2], c='b', s=50)
ax.scatter(Vertices[:,0],Vertices[:,1], Vertices[:,2], color='y', s=1, edgecolors='none')

plt.show()

Using matplotlib backend: MacOSX
