In [1]:
import glob
import time
import numpy as np
np.set_printoptions(suppress=True)

from SmoothSparseWeights_CVXOPT import *

In [2]:
# exampleName="cheburashka"
# poses_folder="poses-2"
# poses_ind=7
# clip_k=4
# handle_num=11


# exampleName="cow"
# poses_folder="poses-2"
# poses_ind=5
# clip_k=4
# handle_num=15


exampleName="wolf"
poses_folder="poses-1"
poses_ind=2
clip_k=4
handle_num=21



weights = {'W_spatial': 0.0}

In [3]:
#### read obj file

### rest_poses:
vertices_obj_path="./models/"+exampleName+"-all/"+exampleName+".obj"
mesh0=TriMesh.FromOBJ_FileName(vertices_obj_path)

### other poses
vertices_obj_dir="./models/"+exampleName+"-all/"+poses_folder+"/"
filenames=glob.glob(vertices_obj_dir+"*.obj")
print(filenames)

mesh1_list=[]
for i in range(len(filenames)):
    mesh1_list.append(TriMesh.FromOBJ_FileName(filenames[i]))


vertices1=vertices1_temp=np.hstack((np.asarray(mesh0.vs),np.ones((len(mesh0.vs),1))))
vertices2=vertices2_temp=np.asarray(mesh1_list[0].vs)
for i in range(1,len(mesh1_list)):
    vertices1=np.hstack((vertices1, vertices1_temp))
    vertices2=np.hstack((vertices2, np.asarray(mesh1_list[i].vs)))
print(vertices1.shape) 
print(vertices2.shape) 
print (vertices1.max())
print (vertices2.max())

['./models/wolf-all/poses-1/wolf-1.obj', './models/wolf-all/poses-1/wolf-2.obj', './models/wolf-all/poses-1/wolf-3.obj', './models/wolf-all/poses-1/wolf-4.obj', './models/wolf-all/poses-1/wolf-5.obj', './models/wolf-all/poses-1/wolf-6.obj']
(5075, 24)
(5075, 18)
3.96582
4.370884


In [4]:
#### read our output of simplex_hull.py 
results_path="./results_pipeline/"+exampleName+"-"+str(handle_num)+"/result.txt"
endmembers, mixing_weights=load_result(results_path)
### endmembers shape is handle * poses * 12??

# ### this is to make sure the 3*4 or 4*3 error does not happen.
# endmembers=endmembers.reshape((-1, 4, 3))
# endmembers=np.transpose(endmembers, (0,2,1))
# endmembers=endmembers.reshape((len(mixing_weights), -1, 12))


endmembers=endmembers.reshape((len(mixing_weights),-1))
mixing_weights=mixing_weights.T


print (endmembers.shape)
print (mixing_weights.shape)
print (mixing_weights[:3])
mixing_weights_clip, grad_zero_indices=clip_first_k_values(mixing_weights, clip_k)
print (mixing_weights_clip[:3])
print ((col_major(mixing_weights_clip)[grad_zero_indices]).sum()) ### should be zero

(21, 72)
(5075, 21)
[[0.1589514  0.0000593  0.00474596 0.00048292 0.0000278  0.03343458
  0.07699286 0.17446554 0.03199314 0.00009963 0.01256247 0.12470764
  0.09002658 0.0000002  0.00000122 0.00001448 0.01316137 0.00123948
  0.00000147 0.00000064 0.27703134]
 [0.15856047 0.00005942 0.00472487 0.0004812  0.00002775 0.03355878
  0.07708042 0.17432981 0.03208895 0.00009982 0.01256983 0.12475939
  0.08994991 0.0000002  0.00000122 0.00001445 0.01320413 0.00123941
  0.00000147 0.00000064 0.27724787]
 [0.15566619 0.00006021 0.00463952 0.00047399 0.00002755 0.03405925
  0.07742135 0.17335098 0.03247172 0.00010021 0.01264691 0.12530878
  0.08969101 0.0000002  0.00000124 0.00001417 0.01345853 0.00124074
  0.00000144 0.00000064 0.27936539]]
[[0.1589514  0.         0.         0.         0.         0.
  0.         0.17446554 0.         0.         0.         0.12470764
  0.         0.         0.         0.         0.         0.
  0.         0.         0.27703134]
 [0.15856047 0.         0.         

In [5]:
scale=find_scale(vertices1)
print (scale)

25.309374465859957


In [6]:
recovered_vertices2=recover_vertices(mixing_weights, vertices1, endmembers)
print (E_RMS_kavan2010(vertices2, recovered_vertices2, scale))

2.90071396789943e-09


In [7]:
recovered_vertices2=recover_vertices(mixing_weights_clip, vertices1, endmembers)
print (E_RMS_kavan2010(vertices2, recovered_vertices2, scale))

initials={'x': col_major(mixing_weights_clip.reshape((-1,len(endmembers)))).reshape((-1,1))}
print (initials['x'].shape)

start=time.time()

res=run(mesh0, mesh1_list, weights, endmembers, mixing_weights.ravel(), grad_zero_indices, initials=initials, choice="vertices_error")

res=res.reshape(mixing_weights.shape)
end=time.time()
print("using time: ", end-start)

recovered_vertices2=recover_vertices(res, vertices1, endmembers)
print (E_RMS_kavan2010(vertices2, recovered_vertices2, scale))

11053.189538523577
(106575, 1)
(5075, 24)
(5075, 18)
5075 6 21
use vertices error as obj
W_spatial 0.0
     pcost       dcost       gap    pres   dres
 0: -5.1893e+03 -1.6349e+05  7e+05  2e+00  9e-14
 1: -4.9252e+03 -7.6784e+04  1e+05  2e-01  1e-13
 2: -4.4254e+03 -2.2096e+04  2e+04  3e-02  8e-14
 3: -4.3111e+03 -1.5928e+04  2e+04  2e-02  5e-14
 4: -4.1611e+03 -1.2431e+04  1e+04  9e-03  4e-14
 5: -4.0384e+03 -8.3427e+03  6e+03  4e-03  3e-14
 6: -3.9481e+03 -6.4799e+03  4e+03  2e-03  3e-14
 7: -3.9053e+03 -5.7786e+03  3e+03  1e-03  3e-14
 8: -3.8582e+03 -5.4216e+03  2e+03  1e-03  3e-14
 9: -3.8012e+03 -5.0659e+03  2e+03  8e-04  2e-14
10: -3.6937e+03 -4.5800e+03  2e+03  5e-04  2e-14
11: -3.6037e+03 -4.2887e+03  1e+03  4e-04  2e-14
12: -3.5228e+03 -4.0252e+03  1e+03  3e-04  1e-14
13: -3.4551e+03 -3.8264e+03  9e+02  2e-04  1e-14
14: -3.4141e+03 -3.7147e+03  8e+02  1e-04  1e-14
15: -3.3839e+03 -3.6422e+03  8e+02  1e-04  1e-14
16: -3.3586e+03 -3.5879e+03  7e+02  1e-04  9e-15
17: -3.3344e+03 

In [8]:
print (res.reshape((-1, len(endmembers)))[:3]) ### should have same zeros as initial input.
print ((col_major(res)[grad_zero_indices]).sum()) ### should be zero
print ((col_major(res)[grad_zero_indices]).max()) ### should be zero

[[ 0.0070222  -0.         -0.         -0.         -0.         -0.
  -0.          0.99235704 -0.         -0.         -0.          0.00033769
  -0.         -0.          0.         -0.         -0.         -0.
   0.         -0.          0.00028307]
 [ 0.00704463 -0.         -0.         -0.         -0.         -0.
  -0.          0.99233282 -0.         -0.         -0.          0.00033861
  -0.         -0.          0.         -0.         -0.         -0.
   0.         -0.          0.00028394]
 [ 0.00705673 -0.         -0.         -0.         -0.         -0.
  -0.          0.99231879 -0.         -0.         -0.          0.00033977
  -0.         -0.          0.         -0.         -0.         -0.
   0.         -0.          0.00028472]]
-2.6291902682773483e-18
1.9461961401592693e-07


In [9]:
print (((1-res.sum(axis=-1))**2).sum()/len(res))
print (res.min(), res.max())

1.4565267391041896e-32
-7.12058257991052e-10 0.9993322057669456


In [10]:
recover_diff= (res.dot(endmembers)-mixing_weights.dot(endmembers))
recover_diff= (recover_diff**2).sum()
print (recover_diff)

849650444.3042293


In [11]:
# #### read gt per vertex transformation 
# groundtruth_names=glob.glob("./models/"+exampleName+"-all/"+exampleName+"-*.DMAT")
# print(groundtruth_names)

# gt_all=None
# for i in range(len(groundtruth_names)):
#     gt=load_DMAT(groundtruth_names[i])
#     gt=gt.T
#     gt=gt.reshape((-1,4,3))
#     gt=np.transpose(gt, (0,2,1)).reshape((-1,12))
#     if gt_all is None:
#         gt_all=gt
#     else:
#         gt_all=np.hstack((gt_all, gt))
    
# print(gt_all.shape)


In [12]:
#### read gt per vertex mixing weights 
groundtruth_names=glob.glob("./models/"+exampleName+"-all/"+exampleName+".DMAT")
print(groundtruth_names)
gt=load_DMAT(groundtruth_names[0])
gt_mixing_weights=gt.T.copy()
print (gt_mixing_weights.shape)

print (((gt_mixing_weights.sum(axis=-1)-1)**2).sum())

['./models/wolf-all/wolf.DMAT']
(5075, 21)
5.575027928616619e-29


In [13]:
### load groundtruth endmember
groundtruth_names=glob.glob("./models/"+exampleName+"-all/"+poses_folder+"/"+exampleName+"-*.Tmat")
print(groundtruth_names)

gt_handles=None
for i in range(len(groundtruth_names)):
    gt=load_Tmat(groundtruth_names[i])
    gt=gt.reshape((-1,4,3))
    gt=np.transpose(gt, (0,2,1)).reshape((-1,12))
    if gt_handles is None:
        gt_handles=gt
    else:
        gt_handles=np.hstack((gt_handles, gt))
    
print(gt_handles.shape)
gt_handles=gt_handles.reshape(len(groundtruth_names), -1, 12)

gt_handles=np.transpose(gt_handles.reshape(-1, len(groundtruth_names), 12), (1,0,2)) ### is this true?

print(gt_handles.shape)

for i in range(len(gt_handles)):
    print (gt_handles[i][2].reshape((3,4)))

test=gt_handles[1][2].reshape((3,4))[:,:3]
print (test.T.dot(test))

['./models/wolf-all/poses-1/wolf-1.Tmat', './models/wolf-all/poses-1/wolf-2.Tmat', './models/wolf-all/poses-1/wolf-3.Tmat', './models/wolf-all/poses-1/wolf-4.Tmat', './models/wolf-all/poses-1/wolf-5.Tmat', './models/wolf-all/poses-1/wolf-6.Tmat']
(21, 72)
(6, 21, 12)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[ 0.963816   0.259295   0.0618401  0.769371 ]
 [-0.215014   0.893333  -0.394619   1.05772  ]
 [-0.157567   0.367044   0.916761   2.30098  ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[ 0.99999966 -0.00000045 -0.00000019]
 [-0.00000045  0.99999904  0.00000028]
 [-0.00000019  0.00000028  0.99999908]]


In [14]:
Vertices=vertices2[:,poses_ind*3:poses_ind*3+3]
print (Vertices.max()) 

# ## use recovered vertices instead.
# recovered_vertices2=recover_vertices(res2, vertices1, endmembers).reshape((len(vertices1),-1))
# Vertices=recovered_vertices2[:,poses_ind*3:poses_ind*3+3]
# print (Vertices.max())

4.370884


In [19]:
print (res.sum(axis=0))
print (res.T.dot(Vertices))
print (res.T.dot(Vertices)/res.sum(axis=0)[...,np.newaxis])

res2=res

res2=res.clip(0,1) ### this is important, when estimate handle position later.
print (((1-res2.sum(axis=-1))**2).sum()/len(res2))

print (res2.sum(axis=0))
print (res2.T.dot(Vertices))
print (res.T.dot(Vertices)/res.sum(axis=0)[...,np.newaxis])


[ 114.99831203   -0.00000068    0.09881087    0.00002178   -0.00000068
    1.00112431    0.93834326 3419.61970791    1.32169375   -0.00000081
    0.18410192    2.14685774 1530.88183922   -0.00000129    0.00000913
    0.00000001    0.52942944   -0.00000085    0.00000232   -0.00000034
    3.27975094]
[[   14.12553996    -9.76827193    68.44383986]
 [   -0.00000002     0.0000003     -0.00000085]
 [    0.07467012    -0.15442368    -0.09883327]
 [   -0.00000182    -0.00002758    -0.00002378]
 [    0.00000002     0.00000022    -0.00000104]
 [    0.14001378    -0.24012559    -2.29365306]
 [    0.38259109    -0.69223847    -0.42439453]
 [  116.26444965  -916.95163943  5370.88972042]
 [    0.19458635    -1.5603663     -0.17317546]
 [   -0.00000001     0.00000042    -0.00000101]
 [   -0.01540853    -0.027064      -0.34523911]
 [    0.20751078    -0.1734099     -0.14548692]
 [  -33.65476872 -1845.20648681   474.51416589]
 [    0.00000001     0.00000104    -0.00000179]
 [    0.00000135    -0.00000

In [20]:
### plot handles corresponding to gt mixing weights, recovered mixing weights, and post-processed mixing weights.
###

eps=1e-30 ### avoid dividing by zero error

gt_handle_position=gt_mixing_weights.T.dot(Vertices)/(gt_mixing_weights.T.sum(axis=-1)[...,np.newaxis]+eps)
recovered_handle_position=mixing_weights.T.dot(Vertices)/(mixing_weights.T.sum(axis=-1)[...,np.newaxis]+eps)
cliped_handle_position=mixing_weights_clip.T.dot(Vertices)/(mixing_weights_clip.T.sum(axis=-1)[...,np.newaxis]+eps)
postprocessed_handle_position=res2.T.dot(Vertices)/(res2.T.sum(axis=-1)[...,np.newaxis]+eps)


%matplotlib 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig= plt.figure()
ax=fig.add_subplot(111, projection='3d')

ax.scatter(gt_handle_position[:,0],gt_handle_position[:,1], gt_handle_position[:,2], c='k', s=50)
ax.scatter(recovered_handle_position[:,0],recovered_handle_position[:,1], recovered_handle_position[:,2], c='r', s=50)
# ax.scatter(cliped_handle_position[:,0],cliped_handle_position[:,1], cliped_handle_position[:,2], c='g', s=50)
ax.scatter(postprocessed_handle_position[:,0],postprocessed_handle_position[:,1], postprocessed_handle_position[:,2], c='b', s=50)
ax.scatter(Vertices[:,0],Vertices[:,1], Vertices[:,2], color='y', s=1, edgecolors='none')

plt.show()

Using matplotlib backend: MacOSX
